### ISSUE TITLE
data download

### ISSUE THREAD

**Issue by chonga2022** [dpeerlab/progressive-plasticity-crc-metastasis#3]
aws s3 ls --no-sign-request s3://dp-laba-data-public/progressive-plasticity-crc-metastasis

An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist

I tried to download data from s3://dp-laba-data-public/progressive-plasticity-crc-metastasis on AWS S3, but I encountered an issue. Could you please help me identify where the problem might be?

**Comment by andrewmoorman** [comment]
Hi, thanks for the heads up - there was a typo in the bucket name (it should be 'dp-lab-data')! I've corrected this and also added direct download links to the files in case you're still having trouble.

**Comment by chonga2022** [comment]
Thank you so much for your direct download links through which I was able to download the h5ad file successfully.  
I have encountered another issue: I don't know where to access additional annotation and enrichment files located in the data/other/ directory, such as the hotspot.p file. Could you provide me with the steps or links to download these files? If there is a specific repository or website where these files are hosted, that information would be extremely helpful.



| |
张舍予
|
|
***@***.***
|
---- Replied Message ----
| From | Andrew ***@***.***> |
| Date | 11/18/2024 09:21 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [dpeerlab/progressive-plasticity-crc-metastasis] data download (Issue #3) |

Hi, thanks for the heads up - there was a typo in the bucket name (it should be 'dp-lab-data')! I've corrected this and also added direct download links to the files in case you're still having trouble.

**Comment by chonga2022** [comment]
Thank you so much for your direct download links through which I was able to download the h5ad file successfully.
I have encountered another issue: I don't know where to access additional annotation and enrichment files located in the data/other/ directory, such as the hotspot.p file. Could you provide me with the steps or links to download these files? If there is a specific repository or website where these files are hosted, that information would be extremely helpful.
